### ISSUE TITLE
Add Chatbot

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Hackathon7/Pacify-final#108]
I want to add a live chatbot feature with Chatwoot using React or Vue js as a GSSoC contributor

**Comment by sampavaranasi** [comment]
@mp3730 https://github.com/girlscript/gssoc-website-new/issues/70

**Comment by Suvraneel** [comment]
@mp3730                    CC: @sampavaranasi 
Resolving from my end. 
(The one GSSoC website was meant as a normal contribution towards making it better & not for scoring purposes)
No need to remove labels or any further action here, its a *valid* contribution. :octocat: @gurjeetsinghvirdee
