### ISSUE TITLE
Add some articles in the "Suggested Mental Health Articles to Read" section

### ISSUE THREAD

**Issue by Rashmisingh-18** [Hackathon7/Pacify-final#111]
Want to add some articles in the "Suggested Mental Health Articles to Read" section
Improving the responsiveness of the website
Improving the footer section

Please assign this issue to me @tarunsinghofficial

**Comment by aytida0606** [comment]
the website already has Suggested Mental Health Articles to Read its not show showing due to some bug.

**Comment by aytida0606** [comment]
> Want to add some articles in the "Suggested Mental Health Articles to Read" section Improving the responsiveness of the website Improving the footer section
> 
> Please assign this issue to me @tarunsinghofficial
the website already has Suggested Mental Health Articles to Read its not show showing due to some bug.
