### ISSUE TITLE
Fix the footer and slide to top functionality

### ISSUE THREAD

**Issue by RajAdwaita** [Hackathon7/Pacify-final#114]
The footer looks abrupt and I think it needs to be fixed also a button needs to be added, which on click will take us to the top of the page which would reduce scrolling effort.

**Comment by tarunsinghofficial** [comment]
> The footer looks abrupt and I think it needs to be fixed also a button needs to be added, which on click will take us to the top of the page which would reduce scrolling effort.

This bug is solved already, please contribute to some other features. Thanks.
