### ISSUE TITLE
add a page for learning 

### ISSUE THREAD

**Issue by Akash-Singh-007** [Hackathon7/Pacify-final#12]
There are several kind of personalities in humans. we can add a page for self education of users. Sections like Symptoms, traits, characteriscs and differenciations

**Comment by smarak-10** [comment]
I am a GSSOC 2022 contributor and i would like to work on this.

**Comment by Adhetya** [comment]
I am a GSSOC 22 contributor. @tarunsinghofficial, @aytida0606 please assign this issue to me

**Comment by Adhetya** [comment]
@aytida0606, sorry was busy with exams. Will send PR by tomorrow 👍
