### ISSUE TITLE
To Create a Scroll To Top Button for the website

### ISSUE THREAD

**Issue by kalyanikakade123** [Hackathon7/Pacify-final#120]
I want to create a scroll to top button for the website so that it help users to get at the top just on click!

**Comment by kalyanikakade123** [comment]
Can you please assign it to me?

**Comment by tarunsinghofficial** [comment]
> I want to create a scroll to top button for the website so that it help users to get at the top just on click!

Thanks for creating this issue, but it has been already solved by another contributor.
