### ISSUE TITLE
Can I add feature of calm yourself down feature?

### ISSUE THREAD

**Issue by Ranjana550** [Hackathon7/Pacify-final#121]
It would be one of the features of the website where users will be able to some peaceful songs or podcasts.

**Comment by Ranjana550** [comment]
If yes, please assign it to me I would love to work on it.

**Comment by Ranjana550** [comment]
Heyy, @tarunsinghofficial 
Can you please raise an issue to add music/podcasts in the features section?
So, from the features section, users will be redirected to the music/podcasts.
![Capture](https://user-images.githubusercontent.com/71266173/159410454-331999e8-4446-4be3-9b96-b54c90913c86.PNG)
Somewhere here, in this section.

**Comment by Ranjana550** [comment]
2 out of 4 tasks done.

**Comment by Ranjana550** [comment]
> Heyy, @tarunsinghofficial Can you please raise an issue to add music/podcasts in the features section? So, from the features section, users will be redirected to the music/podcasts. ![Capture](https://user-images.githubusercontent.com/71266173/159410454-331999e8-4446-4be3-9b96-b54c90913c86.PNG) Somewhere here, in this section.

Heyy @mp3730,  Can you please raise an issue for this?

**Comment by Ranjana550** [comment]
> > 2 out of 4 tasks done.
> 
> Status update ? @Ranjana550

Sorry for the delay. I was little busy with my exams. But, I'll surely finish remaining work by the end of this week.

**Comment by aytida0606** [comment]
commit all changes in one pr @Ranjana550

**Comment by Ranjana550** [comment]
> commit all changes in one pr @Ranjana550

Yes yes. Will do that.
