### ISSUE TITLE
Adding "How to get help" section

### ISSUE THREAD

**Issue by Parul-Mann** [Hackathon7/Pacify-final#122]
People coming to the website need solutions as well, although we have various features available, adding a "how to get help" section is essential to any mental health website to increase awareness about how to go about seeking professional help. 
This section can include government hotline numbers along with other verified resources.

**Comment by Parul-Mann** [comment]
I would like to pick up this issue under GSSOC'22. Kindly assign it to me.

**Comment by komalsoni4** [comment]
please assign this issue to me

**Comment by Parul-Mann** [comment]
I would like to pick up this issue under GSSOC'22. Midway through it. Kindly assign it to me.

**Comment by aachal28** [comment]
Kindly assign me this issue

**Comment by aytida0606** [comment]
> I would like to pick up this issue under GSSOC'22. Midway through it. Kindly assign it to me.

status update ? @Parul-Mann

**Comment by Parul-Mann** [comment]
> > I would like to pick up this issue under GSSOC'22. Midway through it. Kindly assign it to me.
> 
> status update ? @Parul-Mann

On it.
