### ISSUE TITLE
Add some to-read mental health articles

### ISSUE THREAD

**Issue by SHRIYA1706** [Hackathon7/Pacify-final#127]

**Comment by Ranjana550** [comment]
Heyy, @SHRIYA1706 
Is it mandatory to have our own articles? or can we just redirect to those articles from our website?

**Comment by SHRIYA1706** [comment]
It can be redirected if it's good and informative enough. There is no such
rule.

**Comment by pragatisahoo2001** [comment]
Hii sir/ma'am 
I would like to add some good articles on mental health to the website can you please assign this work to me.

**Comment by Polly333** [comment]
Hello Sir/Ma'am,
I would like to add some practical articles on mental health to this website. As this issue is not assigned yet, can you please assign this issue to me?
