### ISSUE TITLE
Add a Favicon

### ISSUE THREAD

**Issue by aaryahjolia** [Hackathon7/Pacify-final#14]
It will be very much amazing if we add a favicon to it.

Assign this issue to me and I will make a great favicon of 'P' letter and I will also place it in website.
I'm a GSSoC'22 contributor.

**Comment by Gurdeep475** [comment]
I would to work on this issue under GSSOC'22.

**Comment by aaryahjolia** [comment]
@Gurdeep475 Assigning issues work on first come first serve basis. If I'm unable to do it in a day after assigned, then you will get a chance.

**Comment by Priyanshu174** [comment]
I am pretty much good at front end web development. I can make awesome favicon for pacify. 
Pls assign this issue .

**Comment by Samridhi015** [comment]
i can work on this issue
