### ISSUE TITLE
Navbar and landing page image can be improved

### ISSUE THREAD

**Issue by DweejaReddy** [Hackathon7/Pacify-final#15]
I am a GSSOC participant and want to work on this issue

I feel navbar could be styled better and the image has the freepik watermark so better image can be choosen

**Comment by adi7yashah** [comment]
I am a participant of GSSOC'22. I want to work on this issue .Can you please aassign me?
I will definitely do this work properly.
I will style navbar and also improve landing page

**Comment by DweejaReddy** [comment]
> I am a participant of GSSOC'22. I want to work on this issue .Can you please aassign me? I will definitely do this work properly. I will style navbar and also improve landing page

I am also a participant of GSSOC'22 and raised this issue. Please look for other issues if you want to contribute
