### ISSUE TITLE
The mobile view of the "Articles to read" can be made better

### ISSUE THREAD

**Issue by Whizz76** [Hackathon7/Pacify-final#16]
Hi, I am Aparna,  a Gssoc'22 contributer. 

I think that the mobile view of the "Articles to read" can be made better. 
![20220301_152902](https://user-images.githubusercontent.com/89126404/156147396-267fe335-ccf8-4292-9820-d45caabb1243.jpg)

I want to solve this issue by improving the styling of the "Articles to read" cards. I have the required frontend skills needed to solve this issue. Please assign it to me.

**Comment by KhushiRana2003** [comment]
Hii.. I am A GSSOC participant and I want to improve this and want to work on this issue..PLz Assign this to me..
