### ISSUE TITLE
Footer in quiz section 

### ISSUE THREAD

**Issue by Areebah03** [Hackathon7/Pacify-final#171]
Quiz section does not have a footer. I want to add it to make the website uniform. Please assign it to me @tarunsinghofficial 
![ss3](https://user-images.githubusercontent.com/85051124/161940962-a1cf12f9-41ca-4e83-a5da-2ee0419aa376.png)
.

**Comment by mp3730** [comment]
You can work on other issues as we didn't add a footer on purpose.

**Comment by Areebah03** [comment]
Yeah sure ! Thank you 😃
