### ISSUE TITLE
I want to improve paciFy

### ISSUE THREAD

**Issue by geetanjali2001** [Hackathon7/Pacify-final#174]
Hi,
I have seen in this website navigation bar is overlapping each other and images are not loading. Here's the screenshot of the problem

![paciffy](https://user-images.githubusercontent.com/100347557/161970117-64722ea3-6750-4789-b6e7-e6306b2002e9.png)
![Screenshot (12)](https://user-images.githubusercontent.com/100347557/161970385-60a50217-7457-4b92-aacd-d2fbd994cfec.png)

**Comment by mp3730** [comment]
Hi, @geetanjali2001 this bug has been removed. You can now work on some other issues.
