### ISSUE TITLE
Improve the previous and next buttton under carousal

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [Hackathon7/Pacify-final#175]
I want to enhance styling of these button in the given below image.

![prev](https://user-images.githubusercontent.com/89297894/161972966-e9894fcf-f24e-43c5-82a1-26fe65e96a55.png)

**Comment by AsmaIbrahimButt** [comment]
@Hackathon7 kindly assign me this issue.I would like to fix it.

**Comment by aaryahjolia** [comment]
Can I work on this ?

**Comment by SHRUTI-SINGH16** [comment]
I would like to work on this issue under GSSoC 2022. Please assign this issue to me.

**Comment by komalsoni4** [comment]
@aytida0606 please assign this task to me

**Comment by Abhilasha-Jairath** [comment]
I would like to work on this issue under GSSoC 2022. Please assign this issue to me.

**Comment by aachal28** [comment]
Kindly assign me this issue

**Comment by Abhilasha-Jairath** [comment]
Can you please check the working and let me know if any changes are required ?

**Comment by aytida0606** [comment]
> Can you please check the working and let me know if any changes are required ?

It seems to be working fine
