### ISSUE TITLE
Improper formatting in about section.

### ISSUE THREAD

**Issue by sanket95droid** [Hackathon7/Pacify-final#187]
Webpages in the About section are overlapping and Images are not visible too in this section.
https://hackathon7.github.io/Pacify-final/html/single.html

![image](https://user-images.githubusercontent.com/77754719/162574552-cca6dab3-138c-46a8-9548-690597352b55.png)
![image](https://user-images.githubusercontent.com/77754719/162574570-6d6c2325-6036-438d-b1cb-5f055d5cd548.png)
GSSoC22

**Comment by mp3730** [comment]
@sanket95droid This issue has been solved. You can work on some other issues.
