### ISSUE TITLE
No sign in and contact page

### ISSUE THREAD

**Issue by vedsom** [Hackathon7/Pacify-final#19]
Hello!! 
I am a GSSOC 2022 contributor, as you can see there is no sign in/register page and contact us page in website, contact is page is really helpful, through this people can join our other social media handles and view important articles, posts etc and they also suggest or put their views through it. 

So please assign me to do this

**Comment by surabhichaubey7** [comment]
hello! I am a GSSOC'22 contributor. Kindly, assign me this issue.

**Comment by J-Harsh** [comment]
I would like to work on this task of making sign up and sign in pages, kindly assign me this issue.
