### ISSUE TITLE
Improve Carousel Buttons Shape

### ISSUE THREAD

**Issue by XZANATOL** [Hackathon7/Pacify-final#198]
Improve the shape of the carousel navigation buttons to improve the User Interface and avoid classic theme.

![image](https://user-images.githubusercontent.com/64689436/163219723-b699b003-a77c-4ac9-a698-96dbe392e63a.png)

Issue made under GSSoC'22 contributions,

**Comment by mp3730** [comment]
@XZANATOL You can work on other issues as this has already been assigned.
