### ISSUE TITLE
Text Formatting and alignment.

### ISSUE THREAD

**Issue by sanket95droid** [Hackathon7/Pacify-final#2]
No proper Alignment of text  on https://hackathon7.github.io/Pacify-final/single.html
Can I get assigned to it?

**Comment by ishika1501** [comment]
@sanket95droid  sir please assign it to me .

**Comment by sanket95droid** [comment]
Same thing I said for issue #3

**Comment by sanket95droid** [comment]
@ishika1501 Same thing I said for issue #3

**Comment by Kanika1309** [comment]
Hi...I am GSSoC'22 participant if this issue is still open please assign it to me.

**Comment by sanket95droid** [comment]
I'm working on it @Kanika1309

**Comment by adi7yashah** [comment]
I am a participant of GSSOC'22. I want to work on this issue .Can you please aassign me?
I will definitely do this work properly.
