### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by DivyanshTungaria-01** [Hackathon7/Pacify-final#22]
Hello!,
I am a GSSOC 2022 contributor. I would like to add **dark theme** option to this website.

**Comment by smarak-10** [comment]
Hi!, 
I am a GSSOC 2022 contributor. I would like to contribute to this project.

**Comment by Srilakshmi-27** [comment]
**Project title:** Adding Dark Theme

**Project description:** Adding a dark theme to the website to make it more preferable for the new age developers.

I am a GSSoC'22 Contributor and I would like to contribute to this project.
