### ISSUE TITLE
Make carousel responsive

### ISSUE THREAD

**Issue by Adhetya** [Hackathon7/Pacify-final#223]
- **Do you want to request a *feature* or report a *bug*?**
- **Do the checklist before filing an issue:**

- [x ] bug report
- [ ] feature request

create a feature request
------------------------------------------------------------------
- [ ] Have an idea for a feature?
- [ ] Provide **screenshots** where appropriate

create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [x ] Provide **screenshots** where appropriate
- [ ] Provide a **minimal code snippet** / example that reproduces the bug.

## Expected Behavior

Carousel should be responsive
## Current Behavior

Carousel is not responsive

## Steps to Reproduce

1.Go to website
2.See article section

<img width="1440" alt="Screenshot 2022-05-06 at 8 39 50 PM" src="https://user-images.githubusercontent.com/20537150/167161434-11e9c788-5a18-4bf2-819b-590441ae2e00.png">

I am GSSOC 22 contributor. Please assign this issue to me

**Comment by aytida0606** [comment]
![res](https://user-images.githubusercontent.com/73810643/168263802-a02ad70c-7f12-4ac4-9f02-edca1e20637c.PNG)
quiz  is out of bounds @Adhetya

**Comment by Adhetya** [comment]
@aytida0606, Yes, but I didn't make modifications to this file. I can create a new issue and fix it
