### ISSUE TITLE
Improving the CSS of Sign-In/Sign-Up Form

### ISSUE THREAD

**Issue by KiranAminPanjwani** [Hackathon7/Pacify-final#243]
- **Do you want to request a *feature* or report a *bug*?**
- **Do the checklist before filing an issue:**

- [X] bug report
- [ ] feature request

create a feature request
------------------------------------------------------------------
- [ ] Have an idea for a feature?
- [ ] Provide **screenshots** where appropriate

create a bug report
------------------------------------------------------------------

Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [x] Provide **screenshots** where appropriate
- [ ] Provide a **minimal code snippet** / example that reproduces the bug.

## Expected Behavior

The form should not be too big.
## Current Behavior

I noticed that the Sign-In form does not have a proper template styling. 

![image](https://user-images.githubusercontent.com/90326051/168868015-6a9d9e8d-d1b0-4a01-aab2-9f2e9cee1384.png)

## Possible Solution

The Sign-In Form's CSS can be improved to look more appealing. I am a GSSOC'22 participant, kindly assign this issue to me. Thank you!
## Steps to Reproduce

1. I will adjust the form size.
2. I will update the font family and font size.
3. I will update the Input styling.

**Comment by aytida0606** [comment]
> another contributor is working on issue related to it , so don't make pr until then ,there might be changes you need to fetch . @KiranAminPanjwani

**Comment by KiranAminPanjwani** [comment]
Acknowledged!

**Comment by KiranAminPanjwani** [comment]
Sure!

**Comment by prathambagadiya** [comment]
i would like to work on this please assign to me

**Comment by karantec** [comment]
please assign me this issue under gSSOC 2023
