### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by Areebah03** [Hackathon7/Pacify-final#245]
- **Do you want to request a *feature* or report a *bug*?**
- **Do the checklist before filing an issue:**

- [x] feature request

create a feature request
------------------------------------------------------------------
- [x] Have an idea for a feature?
- [x] Provide **screenshots** where appropriate

## Expected Behavior
I want to improve UI of navbar. Margin and padding are not so good. Also the leafy border are not looking so good.

## Screenshot

![ss2](https://user-images.githubusercontent.com/85051124/169480252-ee41859a-2c28-4bbc-99ff-9af7ba8f6a38.png)

**Comment by akritimangal** [comment]
hi there, I can change the margin and padding to a better looking view. And by leafy border, do you mean the color of the navbar. If color is the problem, then I can change it in various different shades of green.
