### ISSUE TITLE
Footer : Copyright item is missing in the website.

### ISSUE THREAD

**Issue by Susmita-Dey** [Hackathon7/Pacify-final#28]
I want to add the "Copyright @Pacify, 2022" at the center of the footer.
**I am 2022 GSSOC participant and I want to contribute to this real life project.
Kindly assign this issue to me.**

**Comment by smarak-10** [comment]
I am GSSOC 2022 contributor and i want to contribute by adding copyright @pacify

**Comment by nikitadhona** [comment]
Can i work on this issue?

**Comment by Akshata-Gunapache** [comment]
I am a participant of GSSoC'22 . I am interested in this project . Could you please assign it to me?
