### ISSUE TITLE
Page Scrolling Issue.

### ISSUE THREAD

**Issue by sanket95droid** [Hackathon7/Pacify-final#3]
After clicking on Mental Health Articles button on the navbar, the page does not scroll to the desired "div" on the website.
Can I get assigned to it??

**Comment by ishika1501** [comment]
@sanket95droid   i would like to take this issue , as  I am quite confident with my frontend skills  . sir please assign it to me

**Comment by sanket95droid** [comment]
@ishika1501 actually I'm a contributor and I've raised this issue cuz, I want the mentor to assign it to me.

**Comment by adi7yashah** [comment]
I am a participant of GSSOC'22. I want to work on this issue .Can you please aassign me?
I will definitely do this work properly.
