### ISSUE TITLE
Beautifying website look.

### ISSUE THREAD

**Issue by Priyanshu174** [Hackathon7/Pacify-final#30]
->I will be working on following points:-
      1.Navigation bar needs improvement
      2. Footer must be present
      3. Improvement in color scheme
      4. Responsiveness of website
      5. adding more articles 
      6. alignment and proper spacing

kindly assign this issue to me.

**Comment by Sanghu01** [comment]
I am a gssoc participant can you please assign me this issue?

**Comment by ishika-rg** [comment]
> ->I will be working on following points:- 1.Navigation bar needs improvement 2. Footer must be present 3. Improvement in color scheme 4. Responsiveness of website 5. adding more articles 6. alignment and proper spacing
> 
> kindly assign this issue to me.

Kindly assign this issue to me. I want to work on this.
