### ISSUE TITLE
Adding a feature for practicing meditation

### ISSUE THREAD

**Issue by Vrushali-anil-Chaudhari** [Hackathon7/Pacify-final#31]
we can add a section where meditation sounds can be played for users to meditate

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me. Also add the GSSOC22 label here. Thanks.

**Comment by Vrushali-anil-Chaudhari** [comment]
I am contributor as well so suggested this idea so that I can contribute to it
