### ISSUE TITLE
Adding Logo

### ISSUE THREAD

**Issue by thebhavana** [Hackathon7/Pacify-final#38]
Adding logo to Pacify Website.

Do assign this issue under gssoc'22

**Comment by SonikeshKumar14** [comment]
Hi! I would like to work on this issue under GSSOC`22. Please assign it to me.

**Comment by Sanghu01** [comment]
I am a gssoc'22 participant can you please assign me this issue?

**Comment by Akshata-Gunapache** [comment]
I am a participant of GSSoC'22 . I am interested to resolve this issue . Could you please assign it to me?
