### ISSUE TITLE
Improve UI of navigation bar and add footer to the website

### ISSUE THREAD

**Issue by iamtanya-22** [Hackathon7/Pacify-final#40]

**Comment by iamtanya-22** [comment]
I will beautify the navigation bar of the website and add a footer section to it.
Do assign this issue under gssoc'22.

**Comment by Siddhi-Mundada** [comment]
I would like to Improve UI of navigation bar and add footer to the website by adding animation using CSS some hover effects and in footer will also add social media icons with attractive images.
Kindly request u to assign this issue to me under GSSOC22.

**Comment by codervivek5** [comment]
I would like to improve the UI of the navigation bar and add a footer to the website by adding animation using CSS some hover effects in the footer. I can fix the bug in the navigation bar.


Kindly request u to assign this issue to me under GSSOC22.

**Comment by Siddhi-Mundada** [comment]
I would like to More social media icons in the footer. Would also like to increase the font and size of icons to make it look better by increasing font size and and icon size. Footer section links are also not visible I will fix this bug too.
Please assign this issue to me under GSSOC 22.
