### ISSUE TITLE
Fix typos in the About page and Articles section

### ISSUE THREAD

**Issue by miraehab** [Hackathon7/Pacify-final#42]
<h2>Typos to be fixed:</h2>
<h3> In The About page: </h3>
....conditions that have an <strong>affect</strong> ( effect ) on a person’s....<br>
....<strong>Aditonally</strong> ( Additionally ) , mental health.... <br>
....They are <strong>ususally</strong> ( usually ) a result of poor daily....<br>
<h3> In The Articles section: </h3>
....Suicidal <strong>thoughs</strong> ( thoughts ) among adults are increasing....<br><br>

I would like to work on this issue under GSSOC, kindly assign it to me.

**Comment by Samridhi015** [comment]
i can work on this @miraehab
