### ISSUE TITLE
Fixing the Mental Health Article button

### ISSUE THREAD

**Issue by YalfamIamShaon** [Hackathon7/Pacify-final#43]
First of all great website. But whenever I click on Mental Health Article it does not take me to that section. So @Hackathon7 if you allow me I can fix that and also start my journey as a GSSOC 22 contributor.

**Comment by HarshKumarChoudary** [comment]
I would like to work on this issue. I'm a GSSOC 22 participant. Please assign it to me, if the issue is not resolved yet. Thanks.
