### ISSUE TITLE
Improve styling on cards

### ISSUE THREAD

**Issue by Ashish4321-hub** [Hackathon7/Pacify-final#53]
![IMG_20220304_113116](https://user-images.githubusercontent.com/88235823/156708773-25c00c83-203b-405d-b35b-63a0f56bddea.jpg)
![IMG_20220304_113035](https://user-images.githubusercontent.com/88235823/156708779-09631cf0-bc67-4b0d-bfcf-2a15469fac82.jpg)
This size of cards are not equal to each other.So i want to work on it and more over I want to add animation effects and hovering effects on it .
Please assign me this issue. I'm gssoc 2022 contributor.

**Comment by ishika-rg** [comment]
I want to work on this issue. The cards can be made more interactive and "Articles to Read" section is to be included.
Please assign me this issue.
