### ISSUE TITLE
Fixing font style of "Take a Test"

### ISSUE THREAD

**Issue by Tiya0310** [Hackathon7/Pacify-final#58]
The current font style is too large and doesn't look good, can you assign me this issue? I am looking to contribute to some websites. I am a gssoc'22 participant.

**Comment by Pratiksha-Daphal** [comment]
hey,  @tarunsinghofficial  Can I work on this issue?

**Comment by Akshata-Gunapache** [comment]
@tarunsinghofficial  I am a participant of GSSoC'22 . I am interested in this project . I would like to change the font and make it more beautiful .Could you please assign it to me?
