### ISSUE TITLE
Enhancing the scroll bar

### ISSUE THREAD

**Issue by Simran2337** [Hackathon7/Pacify-final#62]
The scroll bar doesn't fits the theme of the website, it can be reduced and which will make the website look more presentable.
![image](https://user-images.githubusercontent.com/54612637/156872934-e0337994-c4ec-42ff-82c9-4ae73a13b014.png)

If yes, Please assign this issue to me, Will work on its enhancement.
@mp3730 @tarunsinghofficial  please give it a look

**Comment by tarunsinghofficial** [comment]
> The scroll bar doesn't fits the theme of the website, it can be reduced and which will make the website look more presentable. ![image](https://user-images.githubusercontent.com/54612637/156872934-e0337994-c4ec-42ff-82c9-4ae73a13b014.png)
> 
> If yes, Please assign this issue to me, Will work on its enhancement. @mp3730 @tarunsinghofficial please give it a look

Looks good! You can start working on it.
