### ISSUE TITLE
Overlapping Yoga poses and articles section

### ISSUE THREAD

**Issue by Simran2337** [Hackathon7/Pacify-final#63]
![image](https://user-images.githubusercontent.com/54612637/156873141-3df62066-61e8-4ac1-ab2d-1c346b0771ac.png)

Both the section are overlapping each other while the website first loads, it has to be properly styles and put in place

@mp3730  @tarunsinghofficial If its good to go, please assign it to me.

**Comment by tarunsinghofficial** [comment]
Go Ahead.

**Comment by ishika-rg** [comment]
I want to work on this issue. The cards can be made more effective using CSS.
Kindly assign it to me.
