### ISSUE TITLE
Navbar Enhancement

### ISSUE THREAD

**Issue by Simran2337** [Hackathon7/Pacify-final#67]
![image](https://user-images.githubusercontent.com/54612637/156879795-bcdee6fa-832d-4c4c-a022-88412b45e55e.png)
The items on the nav bar aren't correctly placed and grouped also the highlighting doesn't match with the content
you can see that I am on articles section but home is highlighted.

This has to be resolved

@tarunsinghofficial please check and assign it to me so that I can work around it

**Comment by radzhiv25** [comment]
Also interested in doing the same
