### ISSUE TITLE
Change color of cards

### ISSUE THREAD

**Issue by Bhawna147** [Hackathon7/Pacify-final#7]
![image](https://user-images.githubusercontent.com/79100530/156049570-bd67ef40-c9d4-44eb-8f2e-b612d86fb6c6.png)

 I want to change the colour of these cards on hover it appears too dark and the text colour is also too light.

Please assign this issue to me under GSSOC'22.

**Comment by Rhydham2809** [comment]
Hello, I m Gssoc 2022 contributor.
I would like to work on it.

**Comment by akrati-max** [comment]
Hello I am Akati GSSOC'22. I am quite confident with my frontend skills and want to change the colour of  these cards on hover.Please assign it to me.

**Comment by Whizz76** [comment]
Hello I am Aparna, a Gssoc'22 contributer, I would like to solve this issue. Please assign it to me

**Comment by Bhawna147** [comment]
As i raised this issue i would like to work on this please this to me
