### ISSUE TITLE
Adding a home button at the submition of the quiz at the analysis of quiz page.

### ISSUE THREAD

**Issue by AbhinavBattu** [Hackathon7/Pacify-final#70]
There should be home button at the submittion page of the quiz which take you back to the home page. As there is no way back option after you reach your analysis of the quiz.

**Comment by tarunsinghofficial** [comment]
Hello @AbhinavBattu Thanks for creating this issue but unfortunately this has been already done. You can add some other issue (if it has). Thanks once again.
