### ISSUE TITLE
Add Footer to Learn More page same as Main file

### ISSUE THREAD

**Issue by tarunsinghofficial** [Hackathon7/Pacify-final#79]
We want to add a footer to the Learn more section same as on Home page one. Thanks.

**Comment by Simran2337** [comment]
@tarunsinghofficial  I am ready to take up the task
Can u assign to me? Please

**Comment by Simran2337** [comment]
![image](https://user-images.githubusercontent.com/54612637/156912856-a32105c8-2c57-43c6-98a9-90148d6587fb.png)

Heyy !! I did that footer
@tarunsinghofficial

**Comment by Simran2337** [comment]
@ I pushed the code along with the navbar Enhancement section
PR is raised

**Comment by KhushiRana2003** [comment]
PLease Assign this to me i want to work on this issue..
