### ISSUE TITLE
Adding a home button after submittion the quiz.

### ISSUE THREAD

**Issue by AbhinavBattu** [Hackathon7/Pacify-final#9]
There should be home button at the submittion page of the quiz which take you back to the home page. As there is no way back option after you reach your analysis of the quiz.

**Comment by AbhinavBattu** [comment]
Please assign me this issue. I would like to work on it.

**Comment by adi7yashah** [comment]
I am a participant of GSSOC'22. I want to work on this issue .Can you please aassign me?
I will definitely do this work properly.
